[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "libX11",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "libgbm",
  "libxcb",
  "libxkbcommon",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib",
  "xorg.libXScrnSaver",
  "xorg.libxshmfence",
  "xorg.libXtst",
  "gtk3",
  "freetype",
  "harfbuzz",
  "fontconfig",
  "at-spi2-atk",
  "at-spi2-core"
]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
